### PR TITLE
Ensure WatchService gets closed, fixes #8

### LINKED ISSUE #8: WatchService is closeble
Hello :) I guess you have to close WatchService after use

### PR DESCRIPTION
**Pull request by carltonwhitehead**
Moved the WatchService to a local variable assigned using try-with-resources in order to ensure it gets closed. Adjusted some method signatures to account for that move.

### CODE REVIEW

**Comment by carltonwhitehead** [comment]
The unit test I wrote to exercise the fix takes ~22 seconds to execute on my local machine since it exercises the full WatchService lifecycle 768 times in order to exceed current known OS limits in case the WatchService leaks. It has occurred to me that this is very inefficient, and there is probably a better way to verify the bug is fixed.

On my machine locally, the test would typically fail with less than 100 iterations. Lowering the cycle count drastically cuts execution time at the expense of correctness across platforms, which may have higher limits.

So far I have not found a satisfactory solution for exercising the fix efficiently due to one problem or another like above. Ideas welcome!

**Comment by carltonwhitehead** [comment]
Is there any objection to merging this PR as-is?

**Comment by helmbold** [comment]
Sorry ... the only issue was me, having not much time. Thanks for your contribution. I'll bump the version number and create a new release to be published on Maven Central soon.

**Comment by carltonwhitehead** [comment]
@helmbold Could you please do a release containing this change?

**Pull request merged**
